target 'Yunpan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end

pod 'XTlib'
pod 'XTlib/Animations'
pod 'XTlib/CustomUIs'
pod 'UITableView+FDTemplateLayoutCell'
pod 'SSZipArchive'
pod 'FDFullscreenPopGesture'
pod 'CHTCollectionViewWaterfallLayout'
pod 'IQKeyboardManager'
pod 'DACircularProgress'
pod 'LXMButtonImagePosition'
pod 'FTPopOverMenu'
pod 'CYLTableViewPlaceHolder'


end
